### ISSUE TITLE
Framework 4.6.1

### ISSUE THREAD

**Issue by DomCotton** [giacomelli/SalesforceSharp#32]
Hi, I forked to add a field to this project which was fine, however the issue I have now is using your NuGet package with my project which has the framework set to 4.6.1.  Any chance you could make a revision?  When I referenced my local fork it is set to framework 4 and i can reference this from a 4.6.1 project, but when i try to add the NuGet revision 1.0.0 i get the following error message :

Could not install package 'SalesforceSharp 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

Thanks!

**Comment by giacomelli** [comment]
Yes, I changed it from `4.0` to `4.7.2` because this bug #21 and to solve it I needed the ` SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12` that were not available on 4.0.

My mistake was to changed it directly to the 4.7.2, because the `4.5` already had the Tls11 and Tls12 options available.

I will publish a new package version (1.0.1) targeting the Framework 4.5. Is this solve your problem @DomCotton ?

**Comment by DomCotton** [comment]
Hopefully it will :)
Thanks so much.
